-- +goose Up

-- Создание таблицы ongoing_content
CREATE TABLE IF NOT EXISTS ongoing_content
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type        TEXT
        CONSTRAINT ongoing_content_type_length CHECK (LENGTH(type) <= 50) NOT NULL,
    title      TEXT
        CONSTRAINT ongoing_content_title_length CHECK (LENGTH(title) <= 150) NOT NULL,
    poster_upload_id INT,
    release_date TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS genre_ongoing_content
(
    genre_id   INT NOT NULL,
    ongoing_content_id INT NOT NULL,
    FOREIGN KEY (genre_id) REFERENCES genre (id) ON DELETE CASCADE,
    FOREIGN KEY (ongoing_content_id) REFERENCES ongoing_content (id) ON DELETE CASCADE,
    CONSTRAINT genre_ongoing_content_unique UNIQUE (genre_id, ongoing_content_id)
);


-- Вставка данных в таблицу ongoing_content
INSERT INTO ongoing_content (title, poster_upload_id, release_date, type)
VALUES  ('Пророк. История Александра Пушкина', 1, '2025-02-14 00:00:00', 'movie'),
        ('Волшебник Изумрудного города', 2, '2025-01-01 00:00:00', 'movie'),
        ('Ворон', 3, '2024-08-21 00:00:00', 'movie'),
        ('Ждун в кино', 4, '2025-01-01 00:00:00', 'movie'),
        ('Сказосные выходные', 5, '2025-08-07 00:00:00', 'movie'),
        ('Финик 2', 6, '2025-10-23 00:00:00', 'movie'),
        ('Красный шелк', 7, '2025-02-20 00:00:00', 'movie'),
        ('Грязные деньги', 8, '2025-01-16 00:00:00', 'movie'),
        ('Сивка-бурка', 9, '2026-01-01 00:00:00', 'movie'),
        ('Сказка о царе Салтане', 10, '2026-02-19 00:00:00', 'movie');



-- Вставка данных в таблицу genre_ongoing_content
INSERT INTO genre_ongoing_content (genre_id, ongoing_content_id)
VALUES (2, 4),
       (5, 4),
       (10, 3),
       (10, 2),
       (13, 1),
       (9, 5),
       (12, 6),
       (11, 7),
       (6, 8),
       (8, 9),
       (8, 10),
       (23, 10);