version: "3.6"
services:
  goservice:
    build: "."
    ports:
      - "8080"
  nginx:
    build: "./nginx"
    ports:
      - "80:80"
    depends_on:
      - "goservice"
  db:
    image: postgres
    volumes:
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf