version: "3.6"
services:
  # ----------------------------------------------
  # БД: Postgres, Redis, миграции
  # ----------------------------------------------
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: kinoskop
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
  migrations:
    restart: on-failure
    build:
      context: .
      dockerfile: ./docker/migrations.dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
  # ----------------------------------------------
  # Микросервисы: Core, Profanity
  # ----------------------------------------------
  profanity:
    restart: always
    build:
      context: .
      dockerfile: ./docker/profanity.dockerfile
    ports:
      - "8085:8085"
  core:
    restart: always
    build:
      context: .
      dockerfile: ./docker/core.dockerfile
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./config_auth.yaml:/app/config_auth.yaml
      - ./config_static.yaml:/app/config_static.yaml
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        CONTENT_SECRET_KEY: ${CONTENT_SECRET_KEY}
        REDIS_PASSWORD: ${REDIS_PASSWORD}
        S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
        S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - profanity
      - postgres
      - redis
