{
 "title": "Киноскоп",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Система", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Доступно памяти",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Доступно постоянной памяти",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "node_filesystem_avail_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Процессорное время по ядрам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(cpu) (rate(node_cpu_seconds_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Коды ответа", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Рейт 500",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "changes(Kinoskop_requests_total{code=\"500\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Коды ответа",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by(code) (changes(Kinoskop_requests_total{url!~\"/metrics.*\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Хиты по сервисам", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Хиты по Content",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "changes(Kinoskop_requests_total{url=~\"/api/content.*\", method=\"GET\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Хиты по User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "changes(Kinoskop_requests_total{url=~\"/api/user.*\", method!=\"OPTIONS\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Хиты по Compilations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "changes(Kinoskop_requests_total{url=~\"/api/compilation.*\", method!=\"OPTIONS\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Хиты по Auth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "changes(Kinoskop_requests_total{url=~\"/api/auth.*\", method!=\"OPTIONS\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Хиты по Favourite",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "changes(Kinoskop_requests_total{url=~\"/api/favourite.*\", method!=\"OPTIONS\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Хиты по Ongoing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "changes(Kinoskop_requests_total{url=~\"/api/ongoing.*\", method!=\"OPTIONS\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Хиты по Review",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "changes(Kinoskop_requests_total{url=~\"/api/review.*\", method!=\"OPTIONS\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Хиты по Search",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "changes(Kinoskop_requests_total{url=~\"/api/search.*\", method!=\"OPTIONS\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Хиты по Static",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "changes(Kinoskop_requests_total{url=~\"/static.*\", method!=\"OPTIONS\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}