// Code generated by MockGen. DO NOT EDIT.
// Source: ongoing_content.go
//
// Generated by this command:
//
//	mockgen -source=ongoing_content.go -destination=mocks/mock_ongoing_content.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	entity "github.com/go-park-mail-ru/2024_1_Cyberkotletki/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockOngoingContent is a mock of OngoingContent interface.
type MockOngoingContent struct {
	ctrl     *gomock.Controller
	recorder *MockOngoingContentMockRecorder
}

// MockOngoingContentMockRecorder is the mock recorder for MockOngoingContent.
type MockOngoingContentMockRecorder struct {
	mock *MockOngoingContent
}

// NewMockOngoingContent creates a new mock instance.
func NewMockOngoingContent(ctrl *gomock.Controller) *MockOngoingContent {
	mock := &MockOngoingContent{ctrl: ctrl}
	mock.recorder = &MockOngoingContentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOngoingContent) EXPECT() *MockOngoingContentMockRecorder {
	return m.recorder
}

// GetAllReleaseYears mocks base method.
func (m *MockOngoingContent) GetAllReleaseYears() ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllReleaseYears")
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllReleaseYears indicates an expected call of GetAllReleaseYears.
func (mr *MockOngoingContentMockRecorder) GetAllReleaseYears() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllReleaseYears", reflect.TypeOf((*MockOngoingContent)(nil).GetAllReleaseYears))
}

// GetNearestOngoings mocks base method.
func (m *MockOngoingContent) GetNearestOngoings(limit int) ([]*entity.OngoingContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNearestOngoings", limit)
	ret0, _ := ret[0].([]*entity.OngoingContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNearestOngoings indicates an expected call of GetNearestOngoings.
func (mr *MockOngoingContentMockRecorder) GetNearestOngoings(limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNearestOngoings", reflect.TypeOf((*MockOngoingContent)(nil).GetNearestOngoings), limit)
}

// GetOngoingContentByID mocks base method.
func (m *MockOngoingContent) GetOngoingContentByID(id int) (*entity.OngoingContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOngoingContentByID", id)
	ret0, _ := ret[0].(*entity.OngoingContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOngoingContentByID indicates an expected call of GetOngoingContentByID.
func (mr *MockOngoingContentMockRecorder) GetOngoingContentByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOngoingContentByID", reflect.TypeOf((*MockOngoingContent)(nil).GetOngoingContentByID), id)
}

// GetOngoingContentByMonthAndYear mocks base method.
func (m *MockOngoingContent) GetOngoingContentByMonthAndYear(month, year int) ([]*entity.OngoingContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOngoingContentByMonthAndYear", month, year)
	ret0, _ := ret[0].([]*entity.OngoingContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOngoingContentByMonthAndYear indicates an expected call of GetOngoingContentByMonthAndYear.
func (mr *MockOngoingContentMockRecorder) GetOngoingContentByMonthAndYear(month, year any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOngoingContentByMonthAndYear", reflect.TypeOf((*MockOngoingContent)(nil).GetOngoingContentByMonthAndYear), month, year)
}

// IsOngoingContentFinished mocks base method.
func (m *MockOngoingContent) IsOngoingContentFinished(contentID int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsOngoingContentFinished", contentID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsOngoingContentFinished indicates an expected call of IsOngoingContentFinished.
func (mr *MockOngoingContentMockRecorder) IsOngoingContentFinished(contentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsOngoingContentFinished", reflect.TypeOf((*MockOngoingContent)(nil).IsOngoingContentFinished), contentID)
}
