// Code generated by MockGen. DO NOT EDIT.
// Source: search.go
//
// Generated by this command:
//
//	mockgen -source=search.go -destination=mocks/mock_search.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSearch is a mock of Search interface.
type MockSearch struct {
	ctrl     *gomock.Controller
	recorder *MockSearchMockRecorder
}

// MockSearchMockRecorder is the mock recorder for MockSearch.
type MockSearchMockRecorder struct {
	mock *MockSearch
}

// NewMockSearch creates a new mock instance.
func NewMockSearch(ctrl *gomock.Controller) *MockSearch {
	mock := &MockSearch{ctrl: ctrl}
	mock.recorder = &MockSearchMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearch) EXPECT() *MockSearchMockRecorder {
	return m.recorder
}

// SearchContent mocks base method.
func (m *MockSearch) SearchContent(query string) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchContent", query)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchContent indicates an expected call of SearchContent.
func (mr *MockSearchMockRecorder) SearchContent(query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchContent", reflect.TypeOf((*MockSearch)(nil).SearchContent), query)
}

// SearchPerson mocks base method.
func (m *MockSearch) SearchPerson(query string) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchPerson", query)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchPerson indicates an expected call of SearchPerson.
func (mr *MockSearchMockRecorder) SearchPerson(query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchPerson", reflect.TypeOf((*MockSearch)(nil).SearchPerson), query)
}
