// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: profanity.proto

package profanity

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProfanityFilterClient is the client API for ProfanityFilter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProfanityFilterClient interface {
	FilterMessage(ctx context.Context, in *Text, opts ...grpc.CallOption) (*Text, error)
	Ping(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*Nothing, error)
}

type profanityFilterClient struct {
	cc grpc.ClientConnInterface
}

func NewProfanityFilterClient(cc grpc.ClientConnInterface) ProfanityFilterClient {
	return &profanityFilterClient{cc}
}

func (c *profanityFilterClient) FilterMessage(ctx context.Context, in *Text, opts ...grpc.CallOption) (*Text, error) {
	out := new(Text)
	err := c.cc.Invoke(ctx, "/profanity.ProfanityFilter/FilterMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profanityFilterClient) Ping(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/profanity.ProfanityFilter/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfanityFilterServer is the server API for ProfanityFilter service.
// All implementations must embed UnimplementedProfanityFilterServer
// for forward compatibility
type ProfanityFilterServer interface {
	FilterMessage(context.Context, *Text) (*Text, error)
	Ping(context.Context, *Nothing) (*Nothing, error)
	mustEmbedUnimplementedProfanityFilterServer()
}

// UnimplementedProfanityFilterServer must be embedded to have forward compatible implementations.
type UnimplementedProfanityFilterServer struct {
}

func (UnimplementedProfanityFilterServer) FilterMessage(context.Context, *Text) (*Text, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FilterMessage not implemented")
}
func (UnimplementedProfanityFilterServer) Ping(context.Context, *Nothing) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedProfanityFilterServer) mustEmbedUnimplementedProfanityFilterServer() {}

// UnsafeProfanityFilterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProfanityFilterServer will
// result in compilation errors.
type UnsafeProfanityFilterServer interface {
	mustEmbedUnimplementedProfanityFilterServer()
}

func RegisterProfanityFilterServer(s grpc.ServiceRegistrar, srv ProfanityFilterServer) {
	s.RegisterService(&ProfanityFilter_ServiceDesc, srv)
}

func _ProfanityFilter_FilterMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Text)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfanityFilterServer).FilterMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profanity.ProfanityFilter/FilterMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfanityFilterServer).FilterMessage(ctx, req.(*Text))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfanityFilter_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nothing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfanityFilterServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profanity.ProfanityFilter/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfanityFilterServer).Ping(ctx, req.(*Nothing))
	}
	return interceptor(ctx, in, info, handler)
}

// ProfanityFilter_ServiceDesc is the grpc.ServiceDesc for ProfanityFilter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProfanityFilter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "profanity.ProfanityFilter",
	HandlerType: (*ProfanityFilterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FilterMessage",
			Handler:    _ProfanityFilter_FilterMessage_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _ProfanityFilter_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "profanity.proto",
}
