--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2 (Debian 16.2-1.pgdg120+2)
-- Dumped by pg_dump version 16.2 (Debian 16.2-1.pgdg120+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: update_updated_at_column(); Type: FUNCTION; Schema: public; Owner: kinoskop_admin
--

CREATE FUNCTION public.update_updated_at_column() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;


ALTER FUNCTION public.update_updated_at_column() OWNER TO kinoskop_admin;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: compilation; Type: TABLE; Schema: public; Owner: kinoskop_admin
--

CREATE TABLE public.compilation (
    id integer NOT NULL,
    title text NOT NULL,
    compilation_type_id integer NOT NULL,
    poster_upload_id integer NOT NULL,
    CONSTRAINT compilation_title_length CHECK (((length(title) > 0) AND (length(title) <= 50))),
    CONSTRAINT compilation_type_id_positive CHECK ((compilation_type_id > 0))
);


ALTER TABLE public.compilation OWNER TO kinoskop_admin;

--
-- Name: compilation_content; Type: TABLE; Schema: public; Owner: kinoskop_admin
--

CREATE TABLE public.compilation_content (
    compilation_id integer NOT NULL,
    content_id integer NOT NULL
);


ALTER TABLE public.compilation_content OWNER TO kinoskop_admin;

--
-- Name: compilation_id_seq; Type: SEQUENCE; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE public.compilation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.compilation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: compilation_type; Type: TABLE; Schema: public; Owner: kinoskop_admin
--

CREATE TABLE public.compilation_type (
    id integer NOT NULL,
    type text NOT NULL,
    CONSTRAINT compilation_type_length CHECK ((length(type) <= 30))
);


ALTER TABLE public.compilation_type OWNER TO kinoskop_admin;

--
-- Name: compilation_type_id_seq; Type: SEQUENCE; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE public.compilation_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.compilation_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: content; Type: TABLE; Schema: public; Owner: kinoskop_admin
--

CREATE TABLE public.content (
    id integer NOT NULL,
    title text NOT NULL,
    original_title text,
    slogan text,
    budget integer,
    age_restriction integer NOT NULL,
    audience integer,
    imdb numeric(3,1) NOT NULL,
    description text NOT NULL,
    poster_upload_id integer NOT NULL,
    box_office integer,
    marketing_budget integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT content_age_restriction_not_negative CHECK ((age_restriction >= 0)),
    CONSTRAINT content_audience_positive CHECK ((audience >= 0)),
    CONSTRAINT content_box_office_positive CHECK ((box_office >= 0)),
    CONSTRAINT content_budget_positive CHECK ((budget > 0)),
    CONSTRAINT content_imdb CHECK (((imdb >= (0)::numeric) AND (imdb <= (10)::numeric))),
    CONSTRAINT content_marketing_budget_positive CHECK ((marketing_budget >= 0)),
    CONSTRAINT description_length CHECK ((length(description) <= 10000)),
    CONSTRAINT original_title_length CHECK ((length(original_title) <= 150)),
    CONSTRAINT slogan_length CHECK ((length(slogan) <= 150)),
    CONSTRAINT title_length CHECK ((length(title) <= 150))
);


ALTER TABLE public.content OWNER TO kinoskop_admin;

--
-- Name: content_id_seq; Type: SEQUENCE; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE public.content ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.content_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: content_type; Type: TABLE; Schema: public; Owner: kinoskop_admin
--

CREATE TABLE public.content_type (
    id integer NOT NULL,
    content_id integer NOT NULL,
    type text NOT NULL,
    CONSTRAINT type_check CHECK (((type = 'movie'::text) OR (type = 'series'::text)))
);


ALTER TABLE public.content_type OWNER TO kinoskop_admin;

--
-- Name: content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE public.content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: country; Type: TABLE; Schema: public; Owner: kinoskop_admin
--

CREATE TABLE public.country (
    id integer NOT NULL,
    name text NOT NULL,
    CONSTRAINT name_length CHECK ((length(name) <= 64))
);


ALTER TABLE public.country OWNER TO kinoskop_admin;

--
-- Name: country_content; Type: TABLE; Schema: public; Owner: kinoskop_admin
--

CREATE TABLE public.country_content (
    country_id integer NOT NULL,
    content_id integer NOT NULL
);


ALTER TABLE public.country_content OWNER TO kinoskop_admin;

--
-- Name: country_id_seq; Type: SEQUENCE; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE public.country ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.country_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: episode; Type: TABLE; Schema: public; Owner: kinoskop_admin
--

CREATE TABLE public.episode (
    id integer NOT NULL,
    season_id integer NOT NULL,
    episode_number integer NOT NULL,
    title text NOT NULL,
    CONSTRAINT episode_episode_number_positive CHECK ((episode_number > 0)),
    CONSTRAINT episode_title_length CHECK ((length(title) <= 150))
);


ALTER TABLE public.episode OWNER TO kinoskop_admin;

--
-- Name: episode_id_seq; Type: SEQUENCE; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE public.episode ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.episode_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: genre; Type: TABLE; Schema: public; Owner: kinoskop_admin
--

CREATE TABLE public.genre (
    id integer NOT NULL,
    name text,
    CONSTRAINT genre_name_length CHECK ((length(name) <= 32))
);


ALTER TABLE public.genre OWNER TO kinoskop_admin;

--
-- Name: genre_content; Type: TABLE; Schema: public; Owner: kinoskop_admin
--

CREATE TABLE public.genre_content (
    genre_id integer NOT NULL,
    content_id integer NOT NULL
);


ALTER TABLE public.genre_content OWNER TO kinoskop_admin;

--
-- Name: genre_id_seq; Type: SEQUENCE; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE public.genre ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.genre_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: goose_db_version; Type: TABLE; Schema: public; Owner: kinoskop_admin
--

CREATE TABLE public.goose_db_version (
    id integer NOT NULL,
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp without time zone DEFAULT now()
);


ALTER TABLE public.goose_db_version OWNER TO kinoskop_admin;

--
-- Name: goose_db_version_id_seq; Type: SEQUENCE; Schema: public; Owner: kinoskop_admin
--

CREATE SEQUENCE public.goose_db_version_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.goose_db_version_id_seq OWNER TO kinoskop_admin;

--
-- Name: goose_db_version_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: kinoskop_admin
--

ALTER SEQUENCE public.goose_db_version_id_seq OWNED BY public.goose_db_version.id;


--
-- Name: movie; Type: TABLE; Schema: public; Owner: kinoskop_admin
--

CREATE TABLE public.movie (
    id integer NOT NULL,
    content_id integer NOT NULL,
    premiere timestamp without time zone,
    release timestamp without time zone,
    duration integer,
    CONSTRAINT movie_duration_check CHECK ((duration > 0))
);


ALTER TABLE public.movie OWNER TO kinoskop_admin;

--
-- Name: movie_id_seq; Type: SEQUENCE; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE public.movie ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: person; Type: TABLE; Schema: public; Owner: kinoskop_admin
--

CREATE TABLE public.person (
    id integer NOT NULL,
    first_name text NOT NULL,
    last_name text NOT NULL,
    birth_date timestamp without time zone,
    death_date timestamp without time zone,
    start_career timestamp without time zone,
    end_career timestamp without time zone,
    sex character(1) NOT NULL,
    height integer,
    spouse text,
    children text,
    photo_upload_id integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT height_positive CHECK ((height > 50)),
    CONSTRAINT person_check CHECK (((birth_date IS NULL) OR (death_date > birth_date))),
    CONSTRAINT person_check1 CHECK (((start_career IS NULL) OR (end_career > start_career))),
    CONSTRAINT person_children_length CHECK ((length(children) <= 150)),
    CONSTRAINT person_first_name_length CHECK ((length(first_name) <= 30)),
    CONSTRAINT person_gender CHECK (((sex = 'M'::bpchar) OR (sex = 'F'::bpchar))),
    CONSTRAINT person_last_name_length CHECK ((length(last_name) <= 30)),
    CONSTRAINT person_spouse_length CHECK ((length(spouse) <= 50))
);


ALTER TABLE public.person OWNER TO kinoskop_admin;

--
-- Name: person_id_seq; Type: SEQUENCE; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE public.person ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.person_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: person_role; Type: TABLE; Schema: public; Owner: kinoskop_admin
--

CREATE TABLE public.person_role (
    id integer NOT NULL,
    role_id integer NOT NULL,
    person_id integer NOT NULL,
    content_id integer NOT NULL
);


ALTER TABLE public.person_role OWNER TO kinoskop_admin;

--
-- Name: person_role_id_seq; Type: SEQUENCE; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE public.person_role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.person_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: review; Type: TABLE; Schema: public; Owner: kinoskop_admin
--

CREATE TABLE public.review (
    id integer NOT NULL,
    user_id integer NOT NULL,
    content_id integer NOT NULL,
    title text NOT NULL,
    text text NOT NULL,
    content_rating integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT rating_user_positive CHECK (((content_rating >= 1) AND (content_rating <= 10))),
    CONSTRAINT review_text_length CHECK (((length(text) > 0) AND (length(text) <= 10000))),
    CONSTRAINT review_title_length CHECK (((length(title) > 0) AND (length(title) <= 50)))
);


ALTER TABLE public.review OWNER TO kinoskop_admin;

--
-- Name: review_id_seq; Type: SEQUENCE; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE public.review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: review_like; Type: TABLE; Schema: public; Owner: kinoskop_admin
--

CREATE TABLE public.review_like (
    review_id integer NOT NULL,
    user_id integer NOT NULL,
    value boolean NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.review_like OWNER TO kinoskop_admin;

--
-- Name: role; Type: TABLE; Schema: public; Owner: kinoskop_admin
--

CREATE TABLE public.role (
    id integer NOT NULL,
    name text NOT NULL,
    CONSTRAINT role_name_length CHECK ((length(name) <= 30))
);


ALTER TABLE public.role OWNER TO kinoskop_admin;

--
-- Name: role_id_seq; Type: SEQUENCE; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE public.role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: season; Type: TABLE; Schema: public; Owner: kinoskop_admin
--

CREATE TABLE public.season (
    id integer NOT NULL,
    series_id integer NOT NULL,
    year_start integer NOT NULL,
    year_end integer,
    CONSTRAINT season_check CHECK ((year_end >= year_start)),
    CONSTRAINT season_year_end_positive CHECK ((year_end > 0)),
    CONSTRAINT season_year_start_positive CHECK ((year_start > 0))
);


ALTER TABLE public.season OWNER TO kinoskop_admin;

--
-- Name: season_id_seq; Type: SEQUENCE; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE public.season ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.season_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: series; Type: TABLE; Schema: public; Owner: kinoskop_admin
--

CREATE TABLE public.series (
    id integer NOT NULL,
    year_start integer NOT NULL,
    year_end integer,
    content_id integer NOT NULL,
    CONSTRAINT series_check CHECK ((year_end >= year_start)),
    CONSTRAINT series_year_end_positive CHECK ((year_end > 0)),
    CONSTRAINT series_year_start_positive CHECK ((year_start > 0))
);


ALTER TABLE public.series OWNER TO kinoskop_admin;

--
-- Name: series_id_seq; Type: SEQUENCE; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE public.series ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.series_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: static; Type: TABLE; Schema: public; Owner: kinoskop_admin
--

CREATE TABLE public.static (
    id integer NOT NULL,
    name text NOT NULL,
    path text NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT upload_name_length CHECK ((length(name) <= 255)),
    CONSTRAINT upload_path_length CHECK ((length(path) <= 255))
);


ALTER TABLE public.static OWNER TO kinoskop_admin;

--
-- Name: static_id_seq; Type: SEQUENCE; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE public.static ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.static_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: kinoskop_admin
--

CREATE TABLE public.users (
    id integer NOT NULL,
    name text,
    email text NOT NULL,
    password_hashed bytea NOT NULL,
    salt_password bytea NOT NULL,
    avatar_upload_id integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT email_length CHECK ((length(email) <= 256)),
    CONSTRAINT password_hashed_length CHECK ((octet_length(password_hashed) <= 32)),
    CONSTRAINT salt_password_length CHECK ((octet_length(salt_password) <= 8)),
    CONSTRAINT user_name_length CHECK ((length(name) <= 30))
);


ALTER TABLE public.users OWNER TO kinoskop_admin;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: goose_db_version id; Type: DEFAULT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.goose_db_version ALTER COLUMN id SET DEFAULT nextval('public.goose_db_version_id_seq'::regclass);

--
-- Name: compilation_content compilation_content_unique; Type: CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.compilation_content
    ADD CONSTRAINT compilation_content_unique UNIQUE (compilation_id, content_id);


--
-- Name: compilation compilation_pkey; Type: CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.compilation
    ADD CONSTRAINT compilation_pkey PRIMARY KEY (id);


--
-- Name: compilation_type compilation_type_pkey; Type: CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.compilation_type
    ADD CONSTRAINT compilation_type_pkey PRIMARY KEY (id);


--
-- Name: compilation_type compilation_type_type_key; Type: CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.compilation_type
    ADD CONSTRAINT compilation_type_type_key UNIQUE (type);


--
-- Name: compilation compilation_type_unique; Type: CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.compilation
    ADD CONSTRAINT compilation_type_unique UNIQUE (id, compilation_type_id);


--
-- Name: content content_pkey; Type: CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.content
    ADD CONSTRAINT content_pkey PRIMARY KEY (id);


--
-- Name: content_type content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.content_type
    ADD CONSTRAINT content_type_pkey PRIMARY KEY (id);


--
-- Name: country_content country_content_unique; Type: CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.country_content
    ADD CONSTRAINT country_content_unique UNIQUE (country_id, content_id);


--
-- Name: country country_name_key; Type: CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.country
    ADD CONSTRAINT country_name_key UNIQUE (name);


--
-- Name: country country_pkey; Type: CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.country
    ADD CONSTRAINT country_pkey PRIMARY KEY (id);


--
-- Name: episode episode_pkey; Type: CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.episode
    ADD CONSTRAINT episode_pkey PRIMARY KEY (id);


--
-- Name: genre_content genre_content_unique; Type: CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.genre_content
    ADD CONSTRAINT genre_content_unique UNIQUE (genre_id, content_id);


--
-- Name: genre genre_name_key; Type: CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.genre
    ADD CONSTRAINT genre_name_key UNIQUE (name);


--
-- Name: genre genre_pkey; Type: CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.genre
    ADD CONSTRAINT genre_pkey PRIMARY KEY (id);


--
-- Name: goose_db_version goose_db_version_pkey; Type: CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.goose_db_version
    ADD CONSTRAINT goose_db_version_pkey PRIMARY KEY (id);


--
-- Name: movie movie_content_id_key; Type: CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.movie
    ADD CONSTRAINT movie_content_id_key UNIQUE (content_id);


--
-- Name: movie movie_pkey; Type: CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.movie
    ADD CONSTRAINT movie_pkey PRIMARY KEY (id);


--
-- Name: person person_pkey; Type: CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.person
    ADD CONSTRAINT person_pkey PRIMARY KEY (id);


--
-- Name: person_role person_role_pkey; Type: CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.person_role
    ADD CONSTRAINT person_role_pkey PRIMARY KEY (id);


--
-- Name: review_like review_likes_unique; Type: CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.review_like
    ADD CONSTRAINT review_likes_unique UNIQUE (review_id, user_id);


--
-- Name: review review_pkey; Type: CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_pkey PRIMARY KEY (id);


--
-- Name: role role_name_key; Type: CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_name_key UNIQUE (name);


--
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);


--
-- Name: person_role role_unique; Type: CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.person_role
    ADD CONSTRAINT role_unique UNIQUE (person_id, content_id, role_id);


--
-- Name: season season_pkey; Type: CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.season
    ADD CONSTRAINT season_pkey PRIMARY KEY (id);


--
-- Name: series series_pkey; Type: CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.series
    ADD CONSTRAINT series_pkey PRIMARY KEY (id);


--
-- Name: static static_pkey; Type: CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.static
    ADD CONSTRAINT static_pkey PRIMARY KEY (id);


--
-- Name: review user_content_unique; Type: CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT user_content_unique UNIQUE (user_id, content_id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_review_content_id; Type: INDEX; Schema: public; Owner: kinoskop_admin
--

CREATE INDEX idx_review_content_id ON public.review USING btree (content_id);


--
-- Name: idx_review_like_review_id; Type: INDEX; Schema: public; Owner: kinoskop_admin
--

CREATE INDEX idx_review_like_review_id ON public.review_like USING btree (review_id);


--
-- Name: content update_at_content; Type: TRIGGER; Schema: public; Owner: kinoskop_admin
--

CREATE TRIGGER update_at_content BEFORE UPDATE ON public.content FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: person update_at_person; Type: TRIGGER; Schema: public; Owner: kinoskop_admin
--

CREATE TRIGGER update_at_person BEFORE UPDATE ON public.person FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: review update_at_review; Type: TRIGGER; Schema: public; Owner: kinoskop_admin
--

CREATE TRIGGER update_at_review BEFORE UPDATE ON public.review FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: review_like update_at_review_like; Type: TRIGGER; Schema: public; Owner: kinoskop_admin
--

CREATE TRIGGER update_at_review_like BEFORE UPDATE ON public.review_like FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: users update_at_users; Type: TRIGGER; Schema: public; Owner: kinoskop_admin
--

CREATE TRIGGER update_at_users BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: compilation compilation_compilation_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.compilation
    ADD CONSTRAINT compilation_compilation_type_id_fkey FOREIGN KEY (compilation_type_id) REFERENCES public.compilation_type(id) ON DELETE CASCADE;


--
-- Name: compilation_content compilation_content_compilation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.compilation_content
    ADD CONSTRAINT compilation_content_compilation_id_fkey FOREIGN KEY (compilation_id) REFERENCES public.compilation(id) ON DELETE CASCADE;


--
-- Name: compilation_content compilation_content_content_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.compilation_content
    ADD CONSTRAINT compilation_content_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.content(id) ON DELETE CASCADE;


--
-- Name: compilation compilation_poster_upload_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.compilation
    ADD CONSTRAINT compilation_poster_upload_id_fkey FOREIGN KEY (poster_upload_id) REFERENCES public.static(id) ON DELETE SET NULL;


--
-- Name: content content_poster_upload_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.content
    ADD CONSTRAINT content_poster_upload_id_fkey FOREIGN KEY (poster_upload_id) REFERENCES public.static(id) ON DELETE CASCADE;


--
-- Name: content_type content_type_content_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.content_type
    ADD CONSTRAINT content_type_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.content(id) ON DELETE CASCADE;


--
-- Name: country_content country_content_content_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.country_content
    ADD CONSTRAINT country_content_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.content(id) ON DELETE CASCADE;


--
-- Name: country_content country_content_country_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.country_content
    ADD CONSTRAINT country_content_country_id_fkey FOREIGN KEY (country_id) REFERENCES public.country(id) ON DELETE CASCADE;


--
-- Name: episode episode_season_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.episode
    ADD CONSTRAINT episode_season_id_fkey FOREIGN KEY (season_id) REFERENCES public.season(id) ON DELETE CASCADE;


--
-- Name: genre_content genre_content_content_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.genre_content
    ADD CONSTRAINT genre_content_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.content(id) ON DELETE CASCADE;


--
-- Name: genre_content genre_content_genre_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.genre_content
    ADD CONSTRAINT genre_content_genre_id_fkey FOREIGN KEY (genre_id) REFERENCES public.genre(id) ON DELETE CASCADE;


--
-- Name: movie movie_content_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.movie
    ADD CONSTRAINT movie_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.content(id) ON DELETE CASCADE;


--
-- Name: person person_photo_upload_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.person
    ADD CONSTRAINT person_photo_upload_id_fkey FOREIGN KEY (photo_upload_id) REFERENCES public.static(id) ON DELETE SET NULL;


--
-- Name: person_role person_role_content_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.person_role
    ADD CONSTRAINT person_role_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.content(id) ON DELETE CASCADE;


--
-- Name: person_role person_role_person_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.person_role
    ADD CONSTRAINT person_role_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.person(id) ON DELETE CASCADE;


--
-- Name: person_role person_role_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.person_role
    ADD CONSTRAINT person_role_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.role(id) ON DELETE CASCADE;


--
-- Name: review review_content_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.content(id) ON DELETE CASCADE;


--
-- Name: review_like review_like_review_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.review_like
    ADD CONSTRAINT review_like_review_id_fkey FOREIGN KEY (review_id) REFERENCES public.review(id) ON DELETE CASCADE;


--
-- Name: review_like review_like_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.review_like
    ADD CONSTRAINT review_like_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: review review_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: season season_series_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.season
    ADD CONSTRAINT season_series_id_fkey FOREIGN KEY (series_id) REFERENCES public.series(id) ON DELETE CASCADE;


--
-- Name: series series_content_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.series
    ADD CONSTRAINT series_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.content(id) ON DELETE CASCADE;


--
-- Name: users users_avatar_upload_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: kinoskop_admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_avatar_upload_id_fkey FOREIGN KEY (avatar_upload_id) REFERENCES public.static(id) ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--

