// Code generated by MockGen. DO NOT EDIT.
// Source: review.go
//
// Generated by this command:
//
//	mockgen -source=review.go -destination=mocks/mock_review.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	reflect "reflect"

	dto "github.com/go-park-mail-ru/2024_1_Cyberkotletki/internal/entity/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockReview is a mock of Review interface.
type MockReview struct {
	ctrl     *gomock.Controller
	recorder *MockReviewMockRecorder
}

// MockReviewMockRecorder is the mock recorder for MockReview.
type MockReviewMockRecorder struct {
	mock *MockReview
}

// NewMockReview creates a new mock instance.
func NewMockReview(ctrl *gomock.Controller) *MockReview {
	mock := &MockReview{ctrl: ctrl}
	mock.recorder = &MockReviewMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReview) EXPECT() *MockReviewMockRecorder {
	return m.recorder
}

// CreateReview mocks base method.
func (m *MockReview) CreateReview(create dto.ReviewCreate) (*dto.ReviewResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReview", create)
	ret0, _ := ret[0].(*dto.ReviewResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReview indicates an expected call of CreateReview.
func (mr *MockReviewMockRecorder) CreateReview(create any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReview", reflect.TypeOf((*MockReview)(nil).CreateReview), create)
}

// DeleteReview mocks base method.
func (m *MockReview) DeleteReview(reviewID, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteReview", reviewID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteReview indicates an expected call of DeleteReview.
func (mr *MockReviewMockRecorder) DeleteReview(reviewID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReview", reflect.TypeOf((*MockReview)(nil).DeleteReview), reviewID, userID)
}

// EditReview mocks base method.
func (m *MockReview) EditReview(update dto.ReviewUpdate) (*dto.ReviewResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditReview", update)
	ret0, _ := ret[0].(*dto.ReviewResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditReview indicates an expected call of EditReview.
func (mr *MockReviewMockRecorder) EditReview(update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditReview", reflect.TypeOf((*MockReview)(nil).EditReview), update)
}

// GetContentReviewByAuthor mocks base method.
func (m *MockReview) GetContentReviewByAuthor(authorID, contentID int) (*dto.ReviewResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContentReviewByAuthor", authorID, contentID)
	ret0, _ := ret[0].(*dto.ReviewResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContentReviewByAuthor indicates an expected call of GetContentReviewByAuthor.
func (mr *MockReviewMockRecorder) GetContentReviewByAuthor(authorID, contentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContentReviewByAuthor", reflect.TypeOf((*MockReview)(nil).GetContentReviewByAuthor), authorID, contentID)
}

// GetContentReviews mocks base method.
func (m *MockReview) GetContentReviews(contentID, count, page int) (*dto.ReviewResponseList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContentReviews", contentID, count, page)
	ret0, _ := ret[0].(*dto.ReviewResponseList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContentReviews indicates an expected call of GetContentReviews.
func (mr *MockReviewMockRecorder) GetContentReviews(contentID, count, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContentReviews", reflect.TypeOf((*MockReview)(nil).GetContentReviews), contentID, count, page)
}

// GetLatestReviews mocks base method.
func (m *MockReview) GetLatestReviews(count int) (*dto.ReviewResponseList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestReviews", count)
	ret0, _ := ret[0].(*dto.ReviewResponseList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestReviews indicates an expected call of GetLatestReviews.
func (mr *MockReviewMockRecorder) GetLatestReviews(count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestReviews", reflect.TypeOf((*MockReview)(nil).GetLatestReviews), count)
}

// GetReview mocks base method.
func (m *MockReview) GetReview(reviewID int) (*dto.ReviewResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReview", reviewID)
	ret0, _ := ret[0].(*dto.ReviewResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReview indicates an expected call of GetReview.
func (mr *MockReviewMockRecorder) GetReview(reviewID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReview", reflect.TypeOf((*MockReview)(nil).GetReview), reviewID)
}

// GetUserReviews mocks base method.
func (m *MockReview) GetUserReviews(userID, count, page int) (*dto.ReviewResponseList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserReviews", userID, count, page)
	ret0, _ := ret[0].(*dto.ReviewResponseList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserReviews indicates an expected call of GetUserReviews.
func (mr *MockReviewMockRecorder) GetUserReviews(userID, count, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserReviews", reflect.TypeOf((*MockReview)(nil).GetUserReviews), userID, count, page)
}

// IsVotedByUser mocks base method.
func (m *MockReview) IsVotedByUser(userID, reviewID int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsVotedByUser", userID, reviewID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsVotedByUser indicates an expected call of IsVotedByUser.
func (mr *MockReviewMockRecorder) IsVotedByUser(userID, reviewID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsVotedByUser", reflect.TypeOf((*MockReview)(nil).IsVotedByUser), userID, reviewID)
}

// UnVoteReview mocks base method.
func (m *MockReview) UnVoteReview(userID, reviewID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnVoteReview", userID, reviewID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnVoteReview indicates an expected call of UnVoteReview.
func (mr *MockReviewMockRecorder) UnVoteReview(userID, reviewID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnVoteReview", reflect.TypeOf((*MockReview)(nil).UnVoteReview), userID, reviewID)
}

// VoteReview mocks base method.
func (m *MockReview) VoteReview(userID, reviewID int, vote bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VoteReview", userID, reviewID, vote)
	ret0, _ := ret[0].(error)
	return ret0
}

// VoteReview indicates an expected call of VoteReview.
func (mr *MockReviewMockRecorder) VoteReview(userID, reviewID, vote any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VoteReview", reflect.TypeOf((*MockReview)(nil).VoteReview), userID, reviewID, vote)
}
