// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/isAuth": {
            "get": {
                "description": "Проверяет, авторизован ли пользователь",
                "tags": [
                    "Auth"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "default": "session=xxx",
                        "description": "session",
                        "name": "Cookie",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "_csrf": []
                    }
                ],
                "description": "Удаляет сессию",
                "tags": [
                    "Auth"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "default": "session=xxx",
                        "description": "session",
                        "name": "Cookie",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/auth/logoutAll": {
            "post": {
                "security": [
                    {
                        "_csrf": []
                    }
                ],
                "description": "Удаляет все сессии пользователя",
                "tags": [
                    "Auth"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "default": "session=xxx",
                        "description": "session",
                        "name": "Cookie",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/compilation/type/{compilationType}": {
            "get": {
                "description": "Получение списка подборок по id типа подборки",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "compilation"
                ],
                "summary": "Получение списка подборок по типу подборок",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id типа подборки",
                        "name": "compilationType",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CompilationResponseList"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/compilation/types": {
            "get": {
                "description": "Получение списка подборок по id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "compilation"
                ],
                "summary": "Получение списка подборок",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CompilationTypeResponseList"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/compilation/{id}/{page}": {
            "get": {
                "description": "Получение карточек контента подборки по id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "compilation"
                ],
                "summary": "Получение карточек контента подборки",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id подборки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "номер страницы",
                        "name": "page",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CompilationContent"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/content/person/{id}": {
            "get": {
                "description": "Получение персоны по id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "content"
                ],
                "summary": "Получение персоны по id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID персоны",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Person"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/content/{id}": {
            "get": {
                "description": "Получение контента по id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "content"
                ],
                "summary": "Получение контента по id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID контента",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Content"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/playground/ping": {
            "get": {
                "description": "Проверка соединения через классический ping pong",
                "tags": [
                    "Playground"
                ],
                "responses": {
                    "200": {
                        "description": "Pong",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/review": {
            "put": {
                "security": [
                    {
                        "_csrf": []
                    }
                ],
                "description": "Обновить рецензию",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "review"
                ],
                "summary": "Обновить рецензию",
                "parameters": [
                    {
                        "description": "Данные для обновления рецензии",
                        "name": "reviewUpdate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ReviewUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ReviewResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "_csrf": []
                    }
                ],
                "description": "Создать рецензию",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "review"
                ],
                "summary": "Создать рецензию",
                "parameters": [
                    {
                        "description": "Данные для создания рецензии",
                        "name": "reviewCreate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ReviewCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ReviewResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/review/content/{id}/{page}": {
            "get": {
                "description": "Получить рецензии контента",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "review"
                ],
                "summary": "Получить рецензии контента",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID контента",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Номер страницы",
                        "name": "page",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ReviewResponseList"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/review/myReview": {
            "get": {
                "description": "Получить рецензию пользователя к контенту",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "review"
                ],
                "summary": "Получить рецензию пользователя к контенту",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID контента",
                        "name": "content_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ReviewResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/review/recent": {
            "get": {
                "description": "Получить последние рецензии",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "review"
                ],
                "summary": "Получить последние рецензии",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ReviewResponseList"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/review/user/{id}/recent": {
            "get": {
                "description": "Получить последние рецензии пользователя",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "review"
                ],
                "summary": "Получить последние рецензии пользователя",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ReviewResponseList"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/review/user/{id}/{page}": {
            "get": {
                "description": "Получить рецензии пользователя",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "review"
                ],
                "summary": "Получить рецензии пользователя",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Номер страницы",
                        "name": "page",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UserReviewResponseList"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/review/{id}": {
            "get": {
                "description": "Получить рецензию по id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "review"
                ],
                "summary": "Получить рецензию",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID рецензии",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ReviewResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "_csrf": []
                    }
                ],
                "description": "Удалить рецензию",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "review"
                ],
                "summary": "Удалить рецензию",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID рецензии",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/review/{id}/dislike": {
            "put": {
                "security": [
                    {
                        "_csrf": []
                    }
                ],
                "description": "Поставить дизлайк рецензии",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "review"
                ],
                "summary": "Поставить дизлайк рецензии",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID рецензии",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/review/{id}/like": {
            "put": {
                "security": [
                    {
                        "_csrf": []
                    }
                ],
                "description": "Поставить лайк рецензии",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "review"
                ],
                "summary": "Поставить лайк рецензии",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID рецензии",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "_csrf": []
                    }
                ],
                "description": "Убрать лайк с рецензии",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "review"
                ],
                "summary": "Убрать лайк с рецензии",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID рецензии",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/static/{id}": {
            "get": {
                "description": "Получение ссылки на статический файл по id. Возвращает ссылку подобного вида:",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Static"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID статики",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "невалидный id статики",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "404": {
                        "description": "файл не найден",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/user/avatar": {
            "put": {
                "security": [
                    {
                        "_csrf": []
                    }
                ],
                "description": "Позволяет загрузить аватарку пользователя. Необходимо быть авторизованным",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "default": "session=xxx",
                        "description": "session",
                        "name": "Cookie",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "файл с аватаркой",
                        "name": "avatar",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Невалидное изображение",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "security": [
                    {
                        "_csrf": []
                    }
                ],
                "description": "Авторизация пользователя. При успешной авторизации отправляет куки с сессией. Если пользователь уже",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "description": "Данные для входа",
                        "name": "loginData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.Login"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/user/me": {
            "get": {
                "description": "Возвращает id авторизованного пользователя",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "default": "session=xxx",
                        "description": "session",
                        "name": "Cookie",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/user/password": {
            "put": {
                "security": [
                    {
                        "_csrf": []
                    }
                ],
                "description": "Обновляет пароль пользователя. Необходимо быть авторизованным, при этом все сессии пользователя",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "default": "session=xxx",
                        "description": "session",
                        "name": "Cookie",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления пароля",
                        "name": "loginData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdatePassword"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Неверный пароль или невалидный payload",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/user/profile": {
            "get": {
                "description": "Возвращает профиль пользователя по id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пользователя",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UserProfile"
                        }
                    },
                    "400": {
                        "description": "Неверный id",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "_csrf": []
                    }
                ],
                "description": "Позволяет обновить следующие данные пользователя: почта, имя (никнейм). Необходимо быть авторизованным.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "default": "session=xxx",
                        "description": "session",
                        "name": "Cookie",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления профиля",
                        "name": "updateData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UserUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Невалидные данные для обновления профиля",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "security": [
                    {
                        "_csrf": []
                    }
                ],
                "description": "Регистрация пользователя. Сразу же возвращает сессию в cookies",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "description": "Данные для регистрации",
                        "name": "registerData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.Register"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CompilationContent": {
            "type": "object",
            "properties": {
                "compilation_id": {
                    "type": "integer",
                    "format": "int",
                    "example": 1
                },
                "content_id": {
                    "type": "integer",
                    "format": "int",
                    "example": 1
                }
            }
        },
        "dto.CompilationResponse": {
            "type": "object",
            "properties": {
                "compilation_type_id": {
                    "type": "integer",
                    "format": "int",
                    "example": 1
                },
                "content_length": {
                    "type": "integer",
                    "format": "int",
                    "example": 1
                },
                "id": {
                    "type": "integer",
                    "format": "int",
                    "example": 1
                },
                "poster_upload_id": {
                    "type": "integer",
                    "format": "int",
                    "example": 1
                },
                "title": {
                    "type": "string",
                    "format": "string",
                    "example": "The Best"
                }
            }
        },
        "dto.CompilationResponseList": {
            "type": "object",
            "properties": {
                "compilations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CompilationResponse"
                    }
                }
            }
        },
        "dto.CompilationTypeResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int",
                    "example": 1
                },
                "type": {
                    "type": "string",
                    "format": "string",
                    "example": "C"
                }
            }
        },
        "dto.CompilationTypeResponseList": {
            "type": "object",
            "properties": {
                "compilation_types": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CompilationTypeResponse"
                    }
                }
            }
        },
        "dto.Content": {
            "type": "object",
            "properties": {
                "actors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PersonPreview"
                    }
                },
                "ageRestriction": {
                    "type": "integer",
                    "example": 18
                },
                "audience": {
                    "type": "integer",
                    "example": 1000000
                },
                "boxOffice": {
                    "type": "integer",
                    "example": 1000000
                },
                "budget": {
                    "type": "integer",
                    "example": 1000000
                },
                "composers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PersonPreview"
                    }
                },
                "countries": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Россия",
                        "США"
                    ]
                },
                "description": {
                    "type": "string",
                    "example": "Описание фильма или сериала"
                },
                "directors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PersonPreview"
                    }
                },
                "editors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PersonPreview"
                    }
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Боевик",
                        "Драма"
                    ]
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "imdbRating": {
                    "type": "number",
                    "example": 9.1
                },
                "marketing": {
                    "type": "integer",
                    "example": 1000000
                },
                "movie": {
                    "$ref": "#/definitions/dto.MovieContent"
                },
                "operators": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PersonPreview"
                    }
                },
                "originalTitle": {
                    "type": "string",
                    "example": "Batman"
                },
                "posterURL": {
                    "type": "string",
                    "example": "/static/poster.jpg"
                },
                "producers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PersonPreview"
                    }
                },
                "rating": {
                    "type": "number",
                    "example": 9.1
                },
                "series": {
                    "$ref": "#/definitions/dto.SeriesContent"
                },
                "slogan": {
                    "type": "string",
                    "example": "I'm Batman"
                },
                "title": {
                    "type": "string",
                    "example": "Бэтмен"
                },
                "type": {
                    "type": "string",
                    "example": "movie"
                },
                "writers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PersonPreview"
                    }
                }
            }
        },
        "dto.Episode": {
            "type": "object",
            "properties": {
                "episodeNumber": {
                    "type": "integer",
                    "example": 1
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "title": {
                    "type": "string",
                    "example": "Название серии"
                }
            }
        },
        "dto.Login": {
            "type": "object",
            "properties": {
                "login": {
                    "type": "string",
                    "format": "string",
                    "example": "email@email.com"
                },
                "password": {
                    "type": "string",
                    "format": "string",
                    "example": "SecretPassword1!"
                }
            }
        },
        "dto.MovieContent": {
            "type": "object",
            "properties": {
                "duration": {
                    "type": "integer",
                    "example": 134
                },
                "premiere": {
                    "type": "string",
                    "example": "2020-01-01"
                },
                "release": {
                    "type": "string",
                    "example": "2020-01-01"
                }
            }
        },
        "dto.Person": {
            "type": "object",
            "properties": {
                "birthDate": {
                    "type": "string",
                    "example": "1964-09-02"
                },
                "birthPlace": {
                    "type": "string",
                    "example": "Бейрут"
                },
                "children": {
                    "type": "string",
                    "example": "Homer, Bart, Lisa, Maggie"
                },
                "deathDate": {
                    "type": "string",
                    "example": "2021-09-02"
                },
                "endCareer": {
                    "type": "string",
                    "example": "2021-09-02"
                },
                "firstName": {
                    "type": "string",
                    "example": "Киану"
                },
                "height": {
                    "type": "integer",
                    "example": 185
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "lastName": {
                    "type": "string",
                    "example": "Ривз"
                },
                "photoURL": {
                    "type": "string",
                    "example": "/static/photo.jpg"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PreviewContentCard"
                    }
                },
                "sex": {
                    "type": "string",
                    "example": "M"
                },
                "spouse": {
                    "type": "string",
                    "example": "Алисия Викандер"
                },
                "startCareer": {
                    "type": "string",
                    "example": "1984-09-02"
                }
            }
        },
        "dto.PersonPreview": {
            "type": "object",
            "properties": {
                "firstName": {
                    "type": "string",
                    "example": "Киану"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "lastName": {
                    "type": "string",
                    "example": "Ривз"
                }
            }
        },
        "dto.PreviewContentCard": {
            "type": "object",
            "properties": {
                "actors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Том Хэнкс",
                        "Сергей Бодров"
                    ]
                },
                "country": {
                    "type": "string",
                    "example": "Россия"
                },
                "director": {
                    "type": "string",
                    "example": "Тарантино"
                },
                "duration": {
                    "description": "Поля, которые есть только у фильмов",
                    "type": "integer",
                    "example": 134
                },
                "genre": {
                    "type": "string",
                    "example": "Боевик"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "originalTitle": {
                    "type": "string",
                    "example": "Batman"
                },
                "poster": {
                    "type": "string",
                    "example": "/static/poster.jpg"
                },
                "rating": {
                    "type": "number",
                    "example": 9.1
                },
                "releaseYear": {
                    "type": "integer",
                    "example": 2020
                },
                "seasonsNumber": {
                    "description": "Поля, которые есть только у сериалов",
                    "type": "integer",
                    "example": 1
                },
                "title": {
                    "type": "string",
                    "example": "Бэтмен"
                },
                "type": {
                    "type": "string",
                    "example": "movie"
                },
                "yearEnd": {
                    "type": "integer",
                    "example": 2021
                },
                "yearStart": {
                    "type": "integer",
                    "example": 2020
                }
            }
        },
        "dto.Register": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "format": "string",
                    "example": "email@email.com"
                },
                "password": {
                    "type": "string",
                    "format": "string",
                    "example": "SecretPassword1!"
                }
            }
        },
        "dto.ReviewCreateRequest": {
            "type": "object",
            "properties": {
                "contentID": {
                    "type": "integer",
                    "format": "int",
                    "example": 1
                },
                "rating": {
                    "type": "integer",
                    "format": "int",
                    "example": 5
                },
                "text": {
                    "type": "string",
                    "format": "string",
                    "example": "i like it"
                },
                "title": {
                    "type": "string",
                    "format": "string",
                    "example": "Title"
                }
            }
        },
        "dto.ReviewResponse": {
            "type": "object",
            "properties": {
                "authorAvatar": {
                    "type": "string",
                    "format": "string",
                    "example": "avatars/avatar.jpg"
                },
                "authorID": {
                    "type": "integer",
                    "format": "int",
                    "example": 1
                },
                "authorName": {
                    "type": "string",
                    "format": "string",
                    "example": "Author"
                },
                "contentID": {
                    "type": "integer",
                    "format": "int",
                    "example": 1
                },
                "contentName": {
                    "type": "string",
                    "format": "string",
                    "example": "Content"
                },
                "createdAt": {
                    "type": "string",
                    "format": "int",
                    "example": "2022-01-02T15:04:05Z"
                },
                "dislikes": {
                    "type": "integer",
                    "format": "int",
                    "example": 5
                },
                "id": {
                    "type": "integer",
                    "format": "int",
                    "example": 1
                },
                "likes": {
                    "type": "integer",
                    "format": "int",
                    "example": 5
                },
                "rating": {
                    "type": "integer",
                    "format": "int",
                    "example": 5
                },
                "text": {
                    "type": "string",
                    "format": "string",
                    "example": "i like it"
                },
                "title": {
                    "type": "string",
                    "format": "string",
                    "example": "Title"
                }
            }
        },
        "dto.ReviewResponseList": {
            "type": "object",
            "properties": {
                "reviews": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ReviewResponse"
                    }
                }
            }
        },
        "dto.ReviewUpdateRequest": {
            "type": "object",
            "properties": {
                "rating": {
                    "type": "integer",
                    "format": "int",
                    "example": 5
                },
                "reviewID": {
                    "type": "integer",
                    "format": "int",
                    "example": 1
                },
                "text": {
                    "type": "string",
                    "format": "string",
                    "example": "i like it"
                },
                "title": {
                    "type": "string",
                    "format": "string",
                    "example": "Title"
                }
            }
        },
        "dto.Season": {
            "type": "object",
            "properties": {
                "episodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Episode"
                    }
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "yearEnd": {
                    "type": "integer",
                    "example": 2020
                },
                "yearStart": {
                    "type": "integer",
                    "example": 2020
                }
            }
        },
        "dto.SeriesContent": {
            "type": "object",
            "properties": {
                "seasons": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Season"
                    }
                },
                "yearEnd": {
                    "type": "integer",
                    "example": 2020
                },
                "yearStart": {
                    "type": "integer",
                    "example": 2020
                }
            }
        },
        "dto.UpdatePassword": {
            "type": "object",
            "properties": {
                "newPassword": {
                    "type": "string",
                    "format": "string",
                    "example": "NewPassword1!"
                },
                "oldPassword": {
                    "type": "string",
                    "format": "string",
                    "example": "OldPassword1!"
                }
            }
        },
        "dto.UserProfile": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "rating": {
                    "type": "integer"
                }
            }
        },
        "dto.UserReviewResponseList": {
            "type": "object",
            "properties": {
                "me": {
                    "type": "boolean",
                    "format": "bool",
                    "example": true
                },
                "reviews": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ReviewResponse"
                    }
                }
            }
        },
        "dto.UserUpdate": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "echo.HTTPError": {
            "type": "object",
            "properties": {
                "message": {}
            }
        }
    },
    "securityDefinitions": {
        "_csrf": {
            "type": "apiKey",
            "name": "x-csrf",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "API Киноскопа",
	Description:      "сервис Киноскоп (аналог кинопоиска)",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
