basePath: /api
definitions:
  dto.Compilation:
    properties:
      genre:
        example: action
        type: string
      ids:
        example:
        - 1
        - 2
        - 3
        items:
          type: integer
        type: array
    type: object
  dto.Genres:
    properties:
      genres:
        example:
        - action
        - drama
        - comedian
        items:
          type: string
        type: array
    type: object
  dto.Login:
    properties:
      login:
        example: email@email.com
        format: string
        type: string
      password:
        example: SecretPassword1!
        format: string
        type: string
    type: object
  dto.PreviewContentCard:
    properties:
      actors:
        example:
        - Том Хэнкс
        - Сергей Бодров
        items:
          type: string
        type: array
      country:
        example: Россия
        type: string
      director:
        example: Тарантино
        type: string
      duration:
        example: 134
        type: integer
      genre:
        example: Боевик
        type: string
      originalTitle:
        example: Batman
        type: string
      poster:
        example: /static/poster.jpg
        type: string
      rating:
        example: 9.1
        type: number
      releaseYear:
        example: 2020
        type: integer
      title:
        example: Бэтмен
        type: string
    type: object
  dto.Register:
    properties:
      email:
        example: email@email.com
        format: string
        type: string
      password:
        example: SecretPassword1!
        format: string
        type: string
    type: object
  dto.UpdatePassword:
    properties:
      newPassword:
        example: NewPassword1!
        format: string
        type: string
      oldPassword:
        example: OldPassword1!
        format: string
        type: string
    type: object
  dto.UserUpdate:
    properties:
      email:
        type: string
      name:
        type: string
    type: object
  echo.HTTPError:
    properties:
      message: {}
    type: object
info:
  contact: {}
  title: API Киноскопа
  version: "1.0"
paths:
  /auth/isAuth:
    get:
      description: Проверяет, авторизован ли пользователь
      parameters:
      - default: session=xxx
        description: session
        in: header
        name: Cookie
        required: true
        type: string
      responses:
        "200":
          description: OK
        "401":
          description: Не авторизован
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/echo.HTTPError'
      tags:
      - Auth
  /auth/logout:
    post:
      description: Удаляет сессию
      parameters:
      - default: session=xxx
        description: session
        in: header
        name: Cookie
        required: true
        type: string
      responses:
        "200":
          description: OK
      tags:
      - Auth
  /auth/logoutAll:
    post:
      description: Удаляет все сессии пользователя
      parameters:
      - default: session=xxx
        description: session
        in: header
        name: Cookie
        required: true
        type: string
      responses:
        "200":
          description: OK
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/echo.HTTPError'
      tags:
      - Auth
  /collections/compilation:
    get:
      description: Возвращает список всех доступных жанров фильмов и сериалов
      parameters:
      - description: Жанр для составления подборки
        in: query
        name: genre
        required: true
        type: string
      responses:
        "200":
          description: Список с id фильмов указанного жанра
          schema:
            $ref: '#/definitions/dto.Compilation'
        "404":
          description: Такого жанра не существует
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/echo.HTTPError'
      tags:
      - Collections
  /collections/genres:
    get:
      description: Возвращает список всех доступных жанров фильмов и сериалов
      responses:
        "200":
          description: Список с id фильмов указанного жанра
          schema:
            $ref: '#/definitions/dto.Genres'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/echo.HTTPError'
      tags:
      - Collections
  /content/contentPreview:
    get:
      description: Возвращает краткую информацию о фильме или сериале
      parameters:
      - description: ID искомого контента. Контентом может быть как фильм, так и сериал
        in: query
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: Список с id фильмов указанного жанра
          schema:
            $ref: '#/definitions/dto.PreviewContentCard'
        "400":
          description: Требуется указать валидный id контента
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "404":
          description: Контент с таким id не найден
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/echo.HTTPError'
      tags:
      - Content
  /playground/ping:
    get:
      description: Проверка соединения через классический ping pong
      responses:
        "200":
          description: Pong
          schema:
            type: string
      tags:
      - Playground
  /static/{id}:
    get:
      consumes:
      - application/json
      description: 'Получение ссылки на статический файл по id. Возвращает ссылку
        подобного вида:'
      parameters:
      - description: ID статики
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
        "400":
          description: невалидный id статики
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "404":
          description: файл не найден
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: ошибка сервера
          schema:
            $ref: '#/definitions/echo.HTTPError'
      tags:
      - Static
  /user/avatar:
    put:
      consumes:
      - application/json
      description: Позволяет загрузить аватарку пользователя. Необходимо быть авторизованным
      parameters:
      - default: session=xxx
        description: session
        in: header
        name: Cookie
        required: true
        type: string
      - description: файл с аватаркой
        in: formData
        name: avatar
        required: true
        type: file
      responses:
        "200":
          description: OK
        "400":
          description: Невалидное изображение
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "401":
          description: Не авторизован
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/echo.HTTPError'
      tags:
      - User
  /user/login:
    post:
      consumes:
      - application/json
      description: Авторизация пользователя. При успешной авторизации отправляет куки
        с сессией. Если пользователь уже
      parameters:
      - description: Данные для входа
        in: body
        name: loginData
        required: true
        schema:
          $ref: '#/definitions/dto.Login'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      tags:
      - User
  /user/me:
    get:
      consumes:
      - application/json
      description: Возвращает id авторизованного пользователя
      parameters:
      - default: session=xxx
        description: session
        in: header
        name: Cookie
        required: true
        type: string
      responses:
        "200":
          description: OK
        "401":
          description: Не авторизован
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/echo.HTTPError'
      tags:
      - User
  /user/password:
    put:
      consumes:
      - application/json
      description: Обновляет пароль пользователя. Необходимо быть авторизованным,
        при этом все сессии пользователя
      parameters:
      - default: session=xxx
        description: session
        in: header
        name: Cookie
        required: true
        type: string
      - description: Данные для обновления пароля
        in: body
        name: loginData
        required: true
        schema:
          $ref: '#/definitions/dto.UpdatePassword'
      responses:
        "200":
          description: OK
        "400":
          description: Неверный пароль или невалидный payload
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "401":
          description: Не авторизован
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/echo.HTTPError'
      tags:
      - User
  /user/profile:
    get:
      consumes:
      - application/json
      description: Возвращает профиль пользователя по id
      parameters:
      - description: ID пользователя
        in: query
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
        "400":
          description: Неверный id
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "404":
          description: Пользователь не найден
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/echo.HTTPError'
      tags:
      - User
    put:
      consumes:
      - application/json
      description: 'Позволяет обновить следующие данные пользователя: почта, имя (никнейм).
        Необходимо быть авторизованным.'
      parameters:
      - default: session=xxx
        description: session
        in: header
        name: Cookie
        required: true
        type: string
      - description: Данные для обновления профиля
        in: body
        name: updateData
        required: true
        schema:
          $ref: '#/definitions/dto.UserUpdate'
      responses:
        "200":
          description: OK
        "400":
          description: Невалидные данные для обновления профиля
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "401":
          description: Не авторизован
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/echo.HTTPError'
      tags:
      - User
  /user/register:
    post:
      consumes:
      - application/json
      description: Регистрация пользователя. Сразу же возвращает сессию в cookies
      parameters:
      - description: Данные для регистрации
        in: body
        name: registerData
        required: true
        schema:
          $ref: '#/definitions/dto.Register'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      tags:
      - User
swagger: "2.0"
