name: BuildAndTest

on:
  push:
    branches: [ "dev-deploy" ]
  pull_request:
    branches: [ "dev-deploy" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Create env file
      run: |
          touch .env
          echo LISTEN_ADDRESS=0.0.0.0 >> .env
          echo LISTEN_PORT=8080 >> .env
          echo SERVER_MODE=2 >> .env
          echo GEN_SWAGGER=true >> .env
          echo STATIC_DIR= >> .env
          echo CORS=http://0.0.0.0:8000 >> .env
          echo SESSION_ALIVE_TIME=86400 >> .env
          echo COOKIES_SECURE=false >> .env
          echo GRACEFUL_SHUTDOWN_TIME=30 >> .env
          cat .env

    - name: Tidy
      run: go mod tidy

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Update coverage report
      uses: ncruces/go-coverage-report@v0
      with:
        report: true
        chart: true
        amend: true
      if: |
        matrix.os == 'ubuntu-latest' &&
        github.event_name == 'push'  
      continue-on-error: true
    
