name: BasicTest

on:
  push:
    branches: [ "*" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Tidy
      run: go mod tidy

    - name: Test
      run: |
          go test -coverprofile=test.coverage.tmp ./internal/...
          cat test.coverage.tmp | grep -v 'mocks' > test.coverage

    - name: Print coverage
      run: |
        coverage=$(go tool cover -func test.coverage | tail -n 1 | awk '{print $3}')
        echo $coverage
